version : '2'
services:
   redis:
      restart: always
      image: redis
      ports:
          - "6379:6379"
      container_name: redis
      networks:
          - "netName1"
      volumes:
          #- /opt/conf/:/mnt/
          - /usr/local/www/redis:/etc/redis
          #- /usr/local/www/redis/redis.conf:/usr/local/etc/redis/redis.conf
      command: redis-server /etc/redis/redis.conf requirepass dzq123456

networks:
      netName1:
         driver: bridge
