version : '2'
services:
   nginx:
      image: nginx
      ports:
          - "80:80"
      networks:
          - "netName1"
      volumes:
          #- /opt/conf/:/mnt/
          - /srv/static:/usr/share/nginx/html
          - ./conf/nginx.conf:/etc/nginx/ngingx.conf
          - ./conf/conf.d:/etc/nginx/conf.d
          - ./logs:/var/log/nginx
          - ./ssl:/etc/nginx/ssl
networks:
      netName1:
         driver: bridge
