version : '2'
services:
   mysql:
      restart: always
      image: 'mysql/mysql-server:5.7'
      ports:
          - "3306:3306"
      container_name: mysql
      networks:
          - "netName1"
      volumes:
          - ./data:/var/lib/mysql
          - ./:/etc/mysql
          - ./conf/my.cnf:/etc/my.cnf
          - ./init/:/docker-entrypoint-initdb.d/
      environment:
          MYSQL_ROOT_PASSWORD: 123456
         # MYSQL_USER: 'su'
      command:  --default-authentication-plugin=mysql_native_password

networks:
      netName1:
         driver: bridge
